#!/bin/bash

set -ex  # エラー時に終了し、実行コマンドを表示

# 必要なシステムパッケージをインストール
sudo apt update
sudo apt install -y \
    build-essential \
    cmake \
    libsox-dev \
    ffmpeg \
    libasound-dev \
    portaudio19-dev \
    libportaudio2 \
    libportaudiocpp0 \
    python3-pip \
    python3-venv \
    git

# .python-version ファイルから Python のバージョンを取得
PYTHON_VERSION=3.10.0

# 指定された Python バージョンをインストール（未インストールの場合）
if ! pyenv versions --bare | grep -q "^${PYTHON_VERSION}$"; then
    echo "Python ${PYTHON_VERSION} をインストールしています..."
    pyenv install ${PYTHON_VERSION}
else
    echo "Python ${PYTHON_VERSION} は既にインストールされています。"
fi

# ローカルの Python バージョンを設定
pyenv local ${PYTHON_VERSION}

# pip を最新に更新
pip install --upgrade pip

# huggingface_hub をインストール
pip install huggingface_hub

# モデルのダウンロード先ディレクトリを作成
mkdir -p ./models/checkpoints

# モデルのダウンロード
huggingface-cli download fishaudio/fish-speech-1.4 --local-dir ./models/checkpoints/fish-speech-1.4

# $HOME/workspace ディレクトリが存在しない場合は作成
mkdir -p "$HOME/workspace"

# $HOME/workspace/fish-speech が既に存在しない場合のみ git clone を実行
if [ ! -d "$HOME/workspace/fish-speech" ]; then
    echo "Cloning Fish Speech repository into ~/workspace/fish-speech..."
    git clone https://github.com/fishaudio/fish-speech.git "$HOME/workspace/fish-speech"
else
    echo "Fish Speech repository already exists in $HOME/workspace/fish-speech. Skipping clone."
fi

# pyenv がインストールされているかを確認
pyenv install -s

# リポジトリのディレクトリに移動
python -m venv venv
source venv/bin/activate

# pytorchをインストールします。
pip install -r requirements.txt

# リポジトリのディレクトリに移動
cd "$HOME/workspace/fish-speech"
git -C "$HOME/workspace/fish-speech" switch main
git -C "$HOME/workspace/fish-speech" pull origin main

# fish-speechをインストールします。
pip3 install -e .[stable]

cd -

